# Generated by Django 4.2.1 on 2023-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский'), ('Н/У', 'Не указан')], default='М', max_length=3, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
