# Generated by Django 4.2.3 on 2023-08-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='exp',
            field=models.IntegerField(default=100, verbose_name='Опыт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lvl',
            field=models.IntegerField(choices=[(1, 'Новичок'), (2, 'Старший новичок'), (3, 'Продвинутый')], default=1, verbose_name='Уровень'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Читатель'), ('2', 'Писатель'), ('3', 'Модератор'), ('4', 'Администратор'), ('5', 'Спец. Администратор'), ('3', 'Тех. поддержка'), ('3', 'Отдел маркетинга'), ('6', 'Основатель')], default=1, verbose_name='Роль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_background_images/'),
        ),
    ]
