# Generated by Django 4.2.3 on 2023-08-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_user_avatar_alter_user_user_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Читатель'), (2, 'Писатель'), (3, 'Модератор'), (4, 'Администратор'), (5, 'Спец. Администратор'), (3, 'Тех. поддержка'), (3, 'Отдел маркетинга'), (6, 'Основатель')], verbose_name='Роль'),
        ),
    ]
