# Generated by Django 4.2.3 on 2023-08-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Читатель'), (2, 'Писатель'), (3, 'Модератор'), (4, 'Администратор'), (5, 'Спец. Администратор'), (6, 'Тех. поддержка'), (7, 'Отдел маркетинга'), (8, 'Основатель')], verbose_name='Роль'),
        ),
    ]
