# Generated by Django 4.2.3 on 2023-08-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0006_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lvl',
        ),
        migrations.AddField(
            model_name='user',
            name='exp_reader',
            field=models.IntegerField(default='1', verbose_name='Опыт читателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='exp_writer',
            field=models.IntegerField(default=1, verbose_name='Опыт писателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lvl_reader',
            field=models.IntegerField(choices=[(1, 'Начинающий читатель'), (2, 'Любознательный страничник'), (3, 'Путешественник миров бумаги'), (4, 'Словесный исследователь'), (5, 'Строитель мира слов'), (6, 'Мастер словесного искусства'), (7, 'Книжный знаток'), (8, 'Страж библиотеки'), (9, 'Хранитель мудрости книг'), (10, 'Литературный маг'), (11, 'Великий Читатель')], default=1, verbose_name='Уровень читателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lvl_writer',
            field=models.IntegerField(choices=[(1, 'Начинающий читатель'), (2, 'Любознательный страничник'), (3, 'Путешественник миров бумаги'), (4, 'Словесный исследователь'), (5, 'Строитель мира слов'), (6, 'Мастер словесного искусства'), (7, 'Книжный знаток'), (8, 'Страж библиотеки'), (9, 'Хранитель мудрости книг'), (10, 'Литературный маг'), (11, 'Великий Читатель')], default=1, verbose_name='Уровень писателя'),
            preserve_default=False,
        ),
    ]
